# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f3bc52807d3cb47042ca078d10c87815a5e473b87d1d05241b03baa242ba3aaf76034043ba3e24c932546678392a5968e5bc3a76802f522c685c589c3e7a8523

test:
  secret_key_base: 1943c126bbab4424aa7e6b65d2f6c63aac74a96965cc811d18538d0a9402b7893cfa6beda62686e197d5f4eba63e0b82a4e9c1e8834593d4e51192837421425e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
